# Generated by Django 5.0 on 2025-09-11 01:49

import django.core.validators
import relacionamentos.validators.coreia
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('relacionamentos', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='title',
            field=models.CharField(help_text='Digite o título do artigo', max_length=100, validators=[relacionamentos.validators.coreia.tem_coreia], verbose_name='Title'),
        ),
        migrations.AlterField(
            model_name='passport',
            name='number',
            field=models.CharField(help_text='Digite o número do passaporte', max_length=100, unique=True, verbose_name='Number'),
        ),
        migrations.AlterField(
            model_name='person',
            name='cpf',
            field=models.CharField(help_text='Digite o CPF', max_length=11, unique=True, validators=[django.core.validators.MinLengthValidator(11)]),
        ),
        migrations.AlterField(
            model_name='reporter',
            name='cpf',
            field=models.CharField(help_text='Digite o CPF do reporter', max_length=11, unique=True, validators=[django.core.validators.MaxLengthValidator(11)]),
        ),
    ]
