# Generated by Django 5.0 on 2025-09-11 01:54

import django.core.validators
import relacionamentos.validators.validar_cpf
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('relacionamentos', '0003_alter_reporter_cpf'),
    ]

    operations = [
        migrations.AlterField(
            model_name='person',
            name='cpf',
            field=models.CharField(help_text='Digite o CPF', max_length=11, unique=True, validators=[django.core.validators.MinLengthValidator(11), relacionamentos.validators.validar_cpf.valida_cpf]),
        ),
    ]
