# Generated by Django 5.1.3 on 2025-09-11 12:40

import django.db.models.deletion
import relacionamentos.validators.coreia
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('relacionamentos', '0004_alter_person_cpf'),
    ]

    operations = [
        migrations.CreateModel(
            name='Paper',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='Digite o título do artigo', max_length=100, validators=[relacionamentos.validators.coreia.tem_coreia], verbose_name='Title')),
                ('pub_date', models.DateField(help_text='Digite a data de publicação do artigo', verbose_name='Publication Date')),
                ('reporter', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='relacionamentos.reporter')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Publication',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('obs', models.TextField()),
                ('editor', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='relacionamentos.person')),
                ('magazine', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='relacionamentos.magazine')),
                ('paper', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='relacionamentos.paper')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='paper',
            name='magazines',
            field=models.ManyToManyField(blank=True, null=True, through='relacionamentos.Publication', to='relacionamentos.magazine'),
        ),
    ]
