# Generated by Django 5.0 on 2025-08-27 13:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aula', '0002_atividade_nota_atividade_preco_atividade_turno_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='atividade',
            name='nome',
            field=models.CharField(help_text='Digite o nome da atração', max_length=100),
        ),
        migrations.AlterField(
            model_name='atividade',
            name='nota',
            field=models.FloatField(default=0.0, help_text='Deixe uma nota para a atração'),
        ),
        migrations.AlterField(
            model_name='atividade',
            name='preco',
            field=models.DecimalField(decimal_places=2, default=0.0, help_text='Digite o nome da atração em reais. R$ ', max_digits=10, verbose_name='Preço'),
        ),
        migrations.AlterField(
            model_name='atividade',
            name='turno',
            field=models.CharField(blank=True, help_text='Digite o turno em que a atração ocorre', max_length=8, null=True),
        ),
    ]
