# Generated by Django 5.0 on 2025-08-27 14:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aula', '0005_avaliacao_local'),
    ]

    operations = [
        migrations.AlterField(
            model_name='atividade',
            name='duracao',
            field=models.IntegerField(default=0, help_text='Digite a duração da atração em minutos', verbose_name='Duração'),
        ),
        migrations.AlterField(
            model_name='atividade',
            name='endereco',
            field=models.CharField(default='', help_text='Digite o endereço da atração', max_length=200, verbose_name='Endereço'),
        ),
        migrations.AlterField(
            model_name='atividade',
            name='informacoes',
            field=models.TextField(default='', help_text='Digite as informações sobre a atração', max_length=500, verbose_name='Informações'),
        ),
        migrations.AlterField(
            model_name='avaliacao',
            name='comentario',
            field=models.TextField(help_text='Digite o comentário da avaliação', verbose_name='Comentário'),
        ),
        migrations.AlterField(
            model_name='avaliacao',
            name='data_avaliacao',
            field=models.DateField(help_text='Digite a data da avaliação', verbose_name='Data da avaliação'),
        ),
        migrations.AlterField(
            model_name='avaliacao',
            name='data_visita',
            field=models.DateField(help_text='Digite a data da visita', verbose_name='Data da visita'),
        ),
        migrations.AlterField(
            model_name='local',
            name='classificacao',
            field=models.IntegerField(default=0, help_text='Digite a classificação do local', verbose_name='classificação'),
        ),
        migrations.AlterField(
            model_name='local',
            name='endereco',
            field=models.CharField(help_text='Digite o endereço do local', max_length=200, verbose_name='Endereço'),
        ),
        migrations.AlterField(
            model_name='local',
            name='horario_abertura',
            field=models.TimeField(help_text='Digite o horário de abertura do local', verbose_name='Horário de abertura'),
        ),
        migrations.AlterField(
            model_name='local',
            name='horario_fechamento',
            field=models.TimeField(help_text='Digite o horário de fechamento do local', verbose_name='Horário de fechamento'),
        ),
        migrations.AlterField(
            model_name='local',
            name='informacoes',
            field=models.TextField(help_text='Digite o nome do local', max_length=100, verbose_name='Informações'),
        ),
    ]
