# Generated by Django 5.0 on 2025-08-27 14:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aula', '0006_alter_atividade_duracao_alter_atividade_endereco_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Perfil',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_nascimento', models.DateField(help_text='Digite a data de nascimento', verbose_name='Data de nascimento')),
                ('bio', models.TextField(help_text='Digite a biografia do perfil', max_length=255)),
                ('passaporte', models.TextField(help_text='Digite o número do passaporte', max_length=10)),
                ('genero', models.CharField(choices=[('MALE', 'Masculino'), ('FEMALE', 'Feminino'), ('OTHER', 'Outro'), ('NOT SPECIFIED', 'Não especificado')], default='NOT SPECIFIED', help_text='Selecione o gênero', max_length=20, verbose_name='Gênero')),
                ('cidade', models.TextField(help_text='Digite a cidade atual', max_length=255)),
                ('pais', models.CharField(help_text='Digite o país do perfil', max_length=20, verbose_name='País')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
