# Generated by Django 5.0 on 2025-09-11 00:02

import aula.validators.valid
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aula', '0007_perfil'),
    ]

    operations = [
        migrations.AlterField(
            model_name='atividade',
            name='duracao',
            field=models.IntegerField(default=0, help_text='Digite a duração da atração em minutos', validators=[django.core.validators.MinValueValidator(0)], verbose_name='Duração'),
        ),
        migrations.AlterField(
            model_name='atividade',
            name='endereco',
            field=models.CharField(default='', help_text='Digite o endereço da atração', max_length=200, validators=[django.core.validators.MaxLengthValidator(200), django.core.validators.MinLengthValidator(5)], verbose_name='Endereço'),
        ),
        migrations.AlterField(
            model_name='atividade',
            name='informacoes',
            field=models.TextField(default='', help_text='Digite as informações sobre a atração', max_length=500, validators=[django.core.validators.MaxLengthValidator(500)], verbose_name='Informações'),
        ),
        migrations.AlterField(
            model_name='atividade',
            name='nota',
            field=models.FloatField(default=0.0, help_text='Deixe uma nota para a atração', validators=[django.core.validators.MaxValueValidator(5), django.core.validators.MinValueValidator(1)]),
        ),
        migrations.AlterField(
            model_name='atividade',
            name='turno',
            field=models.CharField(blank=True, help_text='Digite o turno em que a atração ocorre', max_length=8, null=True, validators=[django.core.validators.MaxLengthValidator(8)]),
        ),
        migrations.AlterField(
            model_name='atividade',
            name='valor',
            field=models.DecimalField(decimal_places=2, default=0.0, help_text='Digite o valor da atração em reais. R$ ', max_digits=10, validators=[django.core.validators.DecimalValidator(10, 2)]),
        ),
        migrations.AlterField(
            model_name='avaliacao',
            name='acompanhantes',
            field=models.CharField(help_text='Digite os acompanhantes da avaliação', max_length=20, validators=[django.core.validators.MaxLengthValidator(20)]),
        ),
        migrations.AlterField(
            model_name='avaliacao',
            name='likes',
            field=models.IntegerField(help_text='Número de likes da avaliação', validators=[django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AlterField(
            model_name='avaliacao',
            name='nota',
            field=models.IntegerField(help_text='Digite a nota da avaliação', validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)]),
        ),
        migrations.AlterField(
            model_name='avaliacao',
            name='titulo',
            field=models.CharField(help_text='Digite o título da avaliação', max_length=100, validators=[django.core.validators.MaxLengthValidator(100)]),
        ),
        migrations.AlterField(
            model_name='local',
            name='contato',
            field=models.EmailField(help_text='Digite o contato do local', max_length=100, validators=[django.core.validators.MaxLengthValidator(100), django.core.validators.EmailValidator()]),
        ),
        migrations.AlterField(
            model_name='local',
            name='endereco',
            field=models.CharField(help_text='Digite o endereço do local', max_length=200, validators=[django.core.validators.MinLengthValidator(5), django.core.validators.MaxLengthValidator(200), aula.validators.valid.tem_coreia], verbose_name='Endereço'),
        ),
        migrations.AlterField(
            model_name='local',
            name='informacoes',
            field=models.TextField(help_text='Digite o nome do local', max_length=100, validators=[django.core.validators.MaxLengthValidator(200)], verbose_name='Informações'),
        ),
        migrations.AlterField(
            model_name='local',
            name='nome',
            field=models.CharField(help_text='Digite o nome do local', max_length=100, validators=[django.core.validators.MaxLengthValidator(100), django.core.validators.MinLengthValidator(3)]),
        ),
        migrations.AlterField(
            model_name='local',
            name='nota',
            field=models.FloatField(default=0.0, help_text='Deixe uma nota para o local', validators=[django.core.validators.MaxValueValidator(5), django.core.validators.MinValueValidator(1)]),
        ),
        migrations.AlterField(
            model_name='local',
            name='valor',
            field=models.DecimalField(decimal_places=2, default=0.0, help_text='Digite o valor do local em reais. R$ ', max_digits=10, validators=[django.core.validators.DecimalValidator(10, 2), django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AlterField(
            model_name='perfil',
            name='bio',
            field=models.TextField(help_text='Digite a biografia do perfil', max_length=255, validators=[django.core.validators.MaxLengthValidator(255)]),
        ),
        migrations.AlterField(
            model_name='perfil',
            name='cidade',
            field=models.TextField(help_text='Digite a cidade atual', max_length=255, validators=[django.core.validators.MaxLengthValidator(255), django.core.validators.MinValueValidator(3)]),
        ),
        migrations.AlterField(
            model_name='perfil',
            name='genero',
            field=models.CharField(choices=[('MALE', 'Masculino'), ('FEMALE', 'Feminino'), ('OTHER', 'Outro'), ('NOT SPECIFIED', 'Não especificado')], default='NOT SPECIFIED', help_text='Selecione o gênero', max_length=20, validators=[django.core.validators.MaxLengthValidator(20)], verbose_name='Gênero'),
        ),
        migrations.AlterField(
            model_name='perfil',
            name='pais',
            field=models.CharField(help_text='Digite o país do perfil', max_length=20, validators=[django.core.validators.MaxLengthValidator(20), django.core.validators.MinLengthValidator(3)], verbose_name='País'),
        ),
        migrations.AlterField(
            model_name='perfil',
            name='passaporte',
            field=models.TextField(help_text='Digite o número do passaporte', max_length=10, validators=[django.core.validators.MaxLengthValidator(10)]),
        ),
    ]
