# Generated by Django 5.0 on 2025-08-27 13:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aula', '0003_alter_atividade_nome_alter_atividade_nota_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='atividade',
            name='preco',
        ),
        migrations.AddField(
            model_name='atividade',
            name='duracao',
            field=models.IntegerField(default=0, help_text='Digite a duração da atração em minutos'),
        ),
        migrations.AddField(
            model_name='atividade',
            name='endereco',
            field=models.CharField(default='', help_text='Digite o endereço da atração', max_length=200),
        ),
        migrations.AddField(
            model_name='atividade',
            name='guia',
            field=models.BooleanField(default=False, help_text='A atração possui guia?'),
        ),
        migrations.AddField(
            model_name='atividade',
            name='informacoes',
            field=models.TextField(default='', help_text='Digite as informações sobre a atração', max_length=500),
        ),
        migrations.AddField(
            model_name='atividade',
            name='ingresso',
            field=models.BooleanField(default=False, help_text='A atração possui ingresso pago?'),
        ),
        migrations.AddField(
            model_name='atividade',
            name='participantes',
            field=models.IntegerField(default=0, help_text='Digite o número de participantes da atração'),
        ),
        migrations.AddField(
            model_name='atividade',
            name='valor',
            field=models.DecimalField(decimal_places=2, default=0.0, help_text='Digite o valor da atração em reais. R$ ', max_digits=10),
        ),
    ]
