# Generated by Django 5.0 on 2025-08-27 13:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aula', '0004_remove_atividade_preco_atividade_duracao_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Avaliacao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(help_text='Digite o título da avaliação', max_length=100)),
                ('data_avaliacao', models.DateField(help_text='Digite a data da avaliação')),
                ('data_visita', models.DateField(help_text='Digite a data da visita')),
                ('comentario', models.TextField(help_text='Digite o comentário da avaliação')),
                ('nota', models.IntegerField(help_text='Digite a nota da avaliação')),
                ('acompanhantes', models.CharField(help_text='Digite os acompanhantes da avaliação', max_length=20)),
                ('likes', models.IntegerField(help_text='Número de likes da avaliação')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Local',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(help_text='Digite o nome do local', max_length=100)),
                ('endereco', models.CharField(help_text='Digite o endereço do local', max_length=200)),
                ('nota', models.FloatField(default=0.0, help_text='Deixe uma nota para o local')),
                ('horario_abertura', models.TimeField(help_text='Digite o horário de abertura do local')),
                ('horario_fechamento', models.TimeField(help_text='Digite o horário de fechamento do local')),
                ('informacoes', models.TextField(help_text='Digite o nome do local', max_length=100)),
                ('ingresso', models.BooleanField(default=False, help_text='O local possui ingresso pago?')),
                ('valor', models.DecimalField(decimal_places=2, default=0.0, help_text='Digite o valor do local em reais. R$ ', max_digits=10)),
                ('acessibilidade', models.BooleanField(default=False, help_text='O local possui acessibilidade?')),
                ('classificacao', models.IntegerField(default=0, help_text='Digite a classificação do local')),
                ('contato', models.EmailField(help_text='Digite o contato do local', max_length=100)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
