# Generated by Django 5.0 on 2025-09-11 01:48

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aula', '0008_alter_atividade_duracao_alter_atividade_endereco_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='perfil',
            name='cidade',
            field=models.TextField(help_text='Digite a cidade atual', max_length=255, validators=[django.core.validators.MaxLengthValidator(255), django.core.validators.MinLengthValidator(3)]),
        ),
    ]
