# Generated by Django 5.0 on 2025-09-11 00:09

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Magazine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='Digite o título', max_length=30, verbose_name='Title')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Person',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Digite o nome', max_length=100, validators=[django.core.validators.MinLengthValidator(3)], verbose_name='Name')),
                ('birthdate', models.DateField(help_text='Digite a data de nascimento', verbose_name='Birthdate')),
                ('cpf', models.CharField(help_text='Digite o CPF', max_length=11, validators=[django.core.validators.MinLengthValidator(11)])),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Reporter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Digite o nome do reporter', max_length=100, verbose_name='Name')),
                ('email', models.EmailField(help_text='Digite o email do reporter', max_length=100, verbose_name='Email')),
                ('cpf', models.CharField(help_text='Digite o CPF do reporter', max_length=11, validators=[django.core.validators.MaxLengthValidator(11)])),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Passport',
            fields=[
                ('number', models.CharField(help_text='Digite o número do passaporte', max_length=100, verbose_name='Number')),
                ('issue_date', models.DateField(help_text='Digite a data da emissão', verbose_name='Issue Date')),
                ('expiration_date', models.DateField(help_text='Digite a data de expiração', verbose_name='Expiration_date')),
                ('owner', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='relacionamentos.person')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='Digite o título do artigo', max_length=100, verbose_name='Title')),
                ('pub_date', models.DateField(help_text='Digite a data de publicação do artigo', verbose_name='Publication Date')),
                ('magazines', models.ManyToManyField(to='relacionamentos.magazine')),
                ('reporter', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='relacionamentos.reporter')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
