# Generated by Django 5.0 on 2025-09-11 01:53

import django.core.validators
import relacionamentos.validators.validar_cpf
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('relacionamentos', '0002_alter_article_title_alter_passport_number_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reporter',
            name='cpf',
            field=models.CharField(help_text='Digite o CPF do reporter', max_length=11, unique=True, validators=[django.core.validators.MaxLengthValidator(11), relacionamentos.validators.validar_cpf.valida_cpf]),
        ),
    ]
